server:
  port: 7010

logging:
  level:
    project:
      user:
        UserClient: DEBUG
spring:
  application:
    name: Java Persistence Examples
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect