server:
  port: 7010

logging:
  level:
    project:
      user:
        UserClient: DEBUG
spring:
  application:
    name: Java Persistence Examples
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: password
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop