server:
  port: 7010

logging:
  level:
    project:
      user:
        UserClient: DEBUG
spring:
  application:
    name: Java Persistence Examples
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379

redis:
  config:
    username: user
    password: password
    read-timeout: 1s
    max-idle-pool: 8
    max-total-pool: 8
    max-wait: 1s
    min-idle-pool: 0
    nodes:
      - "localhost:7000"
      - "localhost:7001"
      - "localhost:7002"
      - "localhost:7003"
      - "localhost:7004"
      - "localhost:7005"